---
title: CV Lavados
description: Limpieza integral para hogares, empresas y embarcaciones
source: ./
destination: ./_site
url: {{ site.SITE_URL | site.FULL_DOMAIN  }}
# baseurl: "CV-lavados-website"
plugins:
  - jekyll-sitemap
  - jekyll-sass-converter
  - jekyll-environment-variables
sass:
  sass_dir: assets/css
  style: compressed
defaults:
  - scope:
      path: ""
    values:
      layout: default
---

