---
title: CV Lavados
description: Limpieza integral para hogares, empresas y embarcaciones
url: "https://wdr-softwarefactory.github.io" # Reemplaza con tu URL
baseurl: "CV-lavados-website"
plugins:
  - jekyll-sitemap
  - jekyll-sass-converter

sass:
  sass_dir: assets/css
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default
---