---
title: CV Lavados
description: Limpieza integral para hogares, empresas y embarcaciones
url: "https://cvlavados.com.ar" # Reemplaza con tu URL
baseurl: ""
plugins:
  - jekyll-sitemap
  - jekyll-sass-converter
sass:
  sass_dir: assets/css
  style: compressed
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
---