---
title: CV Lavados
description: Limpieza integral para hogares, empresas y embarcaciones
source: ./
destination: ./_site
domain: http://localhost:4000
formspree_id: 
plugins:
  - jekyll-sitemap
  - jekyll-sass-converter
  - jekyll-environment-variables
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: assets/css
  style: compressed
defaults:
  - scope:
      path: ""
    values:
      layout: default
---
